### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by kevinsimper** [siomiz/chrome#1]
Hi @siomiz 

I am running is with Virtualbox and are seeing very poor performance, it takes several seconds every time I click on something.

Do you have a clue or a way to find out what causes it?

Thank you very much :+1:

**Comment by siomiz** [comment]
Hi @kevinsimper 

Are you experiencing the slowness via VNC, or via CRD?

For CRD, all data is (securely) routed through [Google's XMPP server](http://src.chromium.org/viewvc/chrome/trunk/src/remoting/base/service_urls.cc), even when both host and client are on the same local network.
So a click event makes a round-trip to Google, and its response makes another one, which may take a second or two depending on the bandwidth...

Hope this helps!

**Comment by kevinsimper** [comment]
@siomiz Thanks for the answer! :)

> Are you experiencing the slowness via VNC, or via CRD?
> I don't know, how can I find out?

I am using TightVNC to my own Virtualbox instance and simply moving the mouse takes 5 seconds.

**Comment by siomiz** [comment]
Hi @kevinsimper 

It looks like you're using VNC connection.
Could you tell me of your VirtualBox configurations (Is the VirtualBox running on Windows? on OSX? Is it running on the same machine as the TightVNC client? or connected over the Internet?) and TightVNC configurations?
Also, how are you running this "siomiz/chrome" Docker image inside your VirtualBox (what is the guest OS running within VirtualBox?)

Thanks!

(I was able to test using **local** [Docker Toolbox](https://www.docker.com/docker-toolbox) (which uses VirtualBox) on Windows 7 and experienced no lag.)

**Comment by kevinsimper** [comment]
I am using the default from Docker Toolbox on OSX. Yes it is running on the same machine, and yes i am running siomiz/chrome inside the Virtualbox.

I am using the TightVNC-viewer.jar with the default settings.

**Comment by siomiz** [comment]
Unfortunately I don't have an OSX machine to test, but could you try using different VNC viewers/clients to see if the problem persists across them?
