### ISSUE TITLE
is it possible to save chrome config on container start?

### ISSUE THREAD

**Issue by netblink-cobreen** [siomiz/chrome#11]
I'm using siomiz/chrome with my extensions, and sometimes I need to restart docker. How can I save browser config?

**Comment by siomiz** [comment]
Assuming you're accessing via VNC?
`/home/chrome` contains the [Chrome User Data Directory](https://chromium.googlesource.com/chromium/src/+/lkgr/docs/user_data_dir.md#Linux), where all personalizations are stored, so you want to either use a volume or a bind mount there, ex.
```
docker run -d --mount type=bind,source=/path/on/host,target=/home/chrome siomiz/chrome
```
where `/path/on/host` is somewhere on your Docker host that can keep data across restarts.
See https://docs.docker.com/storage/.
