### ISSUE TITLE
Updates broken due to PGP change

### ISSUE THREAD

**Issue by blippercop** [siomiz/chrome#30]
$ docker exec <chrome-container> update

W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B
E: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.

Updates are not possible and the Version of chrome is 89.
Current Chrome is version 110.
Should be a lot of security fixes.

Will there be an update of the docker container that fixes the issue?

**Comment by blippercop** [comment]
@siomiz FYI: Simply adding the the key with
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
and running "docker exec <chrome-container> update" didn't do it for me. I had to run "apt install google-chrome-stable" inside the container and got it updated to Chrome 108. Still updates for security would be nice. If the key gets exchanged and the update routine works again is should be working for a long time again.

**Comment by siomiz** [comment]
Rebuilding will fix the key expiration issue. I will push a new image to Docker Hub.
Thank you!
