### ISSUE TITLE
this docker  image vnc can add password to remote control ? 

### ISSUE THREAD

**Issue by jinhuaxiao** [siomiz/chrome#4]
dear author
this docker  image vnc can add password to remote control ?

**Comment by siomiz** [comment]
Ok, I've added a new tag `:usepw` to the Docker Hub.
Use it to have a password set for the VNC.

Example:
```bash
# (Optional) Create a container/volume with VNC password.
# The following command will ask for a password.
$ docker run -it --user chrome --name vnc-password siomiz/chrome:usepw x11vnc -storepassword
Enter VNC password: 
Verify password:    
Write password to /home/chrome/.vnc/passwd?  [y]/n y
Password written to: /home/chrome/.vnc/passwd

# Mount the volume created above
$ docker run --volumes-from vnc-password siomiz/chrome:usepw

# or use -v option to mount the local password file at /home/chrome/.vnc/passwd
$ docker run -v /path/to/your/vnc-password:/home/chrome/.vnc/passwd siomiz/chrome:usepw
```

I strongly recommend Chrome Remote Desktop or VNC over SSH, though.

**Comment by jinhuaxiao** [comment]
thanks~

**Comment by jinhuaxiao** [comment]
Status: Downloaded newer image for siomiz/chrome:usepw
01/06/2017 07:38:23 passing arg to libvncserver: -storepassword
###############################################################
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@                                                           @#
#@  **  WARNING  **  WARNING  **  WARNING  **  WARNING  **   @#
#@                                                           @#
#@        YOU ARE RUNNING X11VNC WITHOUT A PASSWORD!!        @#
#@                                                           @#
#@  This means anyone with network access to this computer   @#
#@  may be able to view and control your desktop.            @#
#@                                                           @#
#@ >>> If you did not mean to do this Press CTRL-C now!! <<< @#
#@                                                           @#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@                                                           @#
#@  You can create an x11vnc password file by running:       @#
#@                                                           @#
#@       x11vnc -storepasswd password /path/to/passfile      @#
#@  or   x11vnc -storepasswd /path/to/passfile               @#
#@  or   x11vnc -storepasswd                                 @#
#@                                                           @#
#@  (the last one will use ~/.vnc/passwd)                    @#
#@                                                           @#
#@  and then starting x11vnc via:                            @#
#@                                                           @#
#@      x11vnc -rfbauth /path/to/passfile                    @#
#@                                                           @#
#@  an existing ~/.vnc/passwd file from another VNC          @#
#@  application will work fine too.                          @#
#@                                                           @#
#@  You can also use the -passwdfile or -passwd options.     @#
#@  (note -passwd is unsafe if local users are not trusted)  @#
#@                                                           @#
#@  Make sure any -rfbauth and -passwdfile password files    @#
#@  cannot be read by untrusted users.                       @#
#@                                                           @#
#@  Use x11vnc -usepw to automatically use your              @#
#@  ~/.vnc/passwd or ~/.vnc/passwdfile password files.       @#
#@  (and prompt you to create ~/.vnc/passwd if neither       @#
#@  file exists.)  Under -usepw, x11vnc will exit if it      @#
#@  cannot find a password to use.                           @#
#@                                                           @#
#@                                                           @#
#@  Even with a password, the subsequent VNC traffic is      @#
#@  sent in the clear.  Consider tunnelling via ssh(1):      @#
#@                                                           @#
#@    http://www.karlrunge.com/x11vnc/#tunnelling            @#
#@                                                           @#
#@  Or using the x11vnc SSL options: -ssl and -stunnel       @#
#@                                                           @#
#@  Please Read the documention for more info about          @#
#@  passwords, security, and encryption.                     @#
#@                                                           @#
#@    http://www.karlrunge.com/x11vnc/faq.html#faq-passwd    @#
#@                                                           @#
#@  To disable this warning use the -nopw option, or put     @#
#@  'nopw' on a line in your ~/.x11vncrc file.               @#
#@                                                           @#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
###############################################################
01/06/2017 07:38:24 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 1
01/06/2017 07:38:24 XOpenDisplay("") failed.
01/06/2017 07:38:24 Trying again with XAUTHLOCALHOSTNAME=localhost ...
01/06/2017 07:38:24 
01/06/2017 07:38:24 *** XOpenDisplay failed. No -display or DISPLAY.
01/06/2017 07:38:24 *** Trying ":0" in 4 seconds.  Press Ctrl-C to abort.
01/06/2017 07:38:24 *** 1 2 3 4 
01/06/2017 07:38:28 XOpenDisplay(":0") failed.
01/06/2017 07:38:28 Trying again with XAUTHLOCALHOSTNAME=localhost ...
01/06/2017 07:38:28 XOpenDisplay(":0") failed.
01/06/2017 07:38:28 Trying again with unset XAUTHLOCALHOSTNAME ...
01/06/2017 07:38:28 

01/06/2017 07:38:28 ***************************************
01/06/2017 07:38:28 *** XOpenDisplay failed (:0)

*** x11vnc was unable to open the X DISPLAY: ":0", it cannot continue.
*** There may be "Xlib:" error messages above with details about the failure.

Some tips and guidelines:

** An X server (the one you wish to view) must be running before x11vnc is
   started: x11vnc does not start the X server.  (however, see the -create
   option if that is what you really want).

** You must use -display <disp>, -OR- set and export your $DISPLAY
   environment variable to refer to the display of the desired X server.
 - Usually the display is simply ":0" (in fact x11vnc uses this if you forget
   to specify it), but in some multi-user situations it could be ":1", ":2",
   or even ":137".  Ask your administrator or a guru if you are having
   difficulty determining what your X DISPLAY is.

** Next, you need to have sufficient permissions (Xauthority) 
   to connect to the X DISPLAY.   Here are some Tips:

 - Often, you just need to run x11vnc as the user logged into the X session.
   So make sure to be that user when you type x11vnc.
 - Being root is usually not enough because the incorrect MIT-MAGIC-COOKIE
   file may be accessed.  The cookie file contains the secret key that
   allows x11vnc to connect to the desired X DISPLAY.
 - You can explicitly indicate which MIT-MAGIC-COOKIE file should be used
   by the -auth option, e.g.:
       x11vnc -auth /home/someuser/.Xauthority -display :0
       x11vnc -auth /tmp/.gdmzndVlR -display :0
   you must have read permission for the auth file.
   See also '-auth guess' and '-findauth' discussed below.

** If NO ONE is logged into an X session yet, but there is a greeter login
   program like "gdm", "kdm", "xdm", or "dtlogin" running, you will need
   to find and use the raw display manager MIT-MAGIC-COOKIE file.
   Some examples for various display managers:

     gdm:     -auth /var/gdm/:0.Xauth
              -auth /var/lib/gdm/:0.Xauth
     kdm:     -auth /var/lib/kdm/A:0-crWk72
              -auth /var/run/xauth/A:0-crWk72
     xdm:     -auth /var/lib/xdm/authdir/authfiles/A:0-XQvaJk
     dtlogin: -auth /var/dt/A:0-UgaaXa

   Sometimes the command "ps wwwwaux | grep auth" can reveal the file location.

   Starting with x11vnc 0.9.9 you can have it try to guess by using:

              -auth guess

   (see also the x11vnc -findauth option.)

   Only root will have read permission for the file, and so x11vnc must be run
   as root (or copy it).  The random characters in the filenames will of course
   change and the directory the cookie file resides in is system dependent.

See also: http://www.karlrunge.com/x11vnc/faq.html

-----------------------------------
when I run this cmd like yours  ,but it's can't work

**Comment by jinhuaxiao** [comment]
I konw what's wrong ,

$ docker run -it --user chrome --name vnc-password siomiz/chrome:usepw x11vnc -storepassword

should be
$ docker run -it --user chrome --name vnc-password siomiz/chrome:usepw x11vnc -storepasswd

**Comment by siomiz** [comment]
I'll update README with the correct info.
