### ISSUE TITLE
usepwブランチは必要ですか？

### ISSUE THREAD

**Issue by tukiyo** [siomiz/chrome#7]
siomizさま。"Google 入力ツール"拡張機能を追加して、便利に使わせていただいています。
さて、usepwブランチの使い方についてwikiにも無かったためなんだろうかと思いましたが起動オプションがちょっと違うのですね。
しかしvncserverへのパスワード有り接続方法はmasterブランチのもので以下方法で接続できましたことを報告いたします。

* パスワードの作成

```sh
# abcdという接続用パスワードを指定
echo abcd | vncpasswd -f > vncpasswd
```

```sh
# データーコンテナの作成
docker run -d \
 --name chrome-profile \
 siomiz/chrome

# chromeコンテナ起動
docker run -d \
 --volumes-from chrome-profile \
 -v $(pwd)/vncpasswd:/home/chrome/.vnc/passwd \
 -p 5900:5900 \
 siomiz/chrome
```

(ubuntu18.04版も楽しみにしております)

**Comment by siomiz** [comment]
@tukiyo さま

`master`ブランチ・`:latest`タグの方に、[VPCパスワード設定の機能を追加](https://github.com/siomiz/chrome/commit/ef44089d0f6d6557a2b12d9dc60941d13d7cd437#diff-44fd0c17be30c41d1959154f2ef5ff4e)して以来、`usepw`の方は放置されてしまっている状況です。
READMEの方にその旨を明記させていただきます。
（ちなみに`docker secret`にも、シークレット名`vncpasswd`で対応しています。）

`ubuntu:18.04`ベースについても、目下テスト中です。

**Comment by siomiz** [comment]
[Docker Hub上の該当イメージ](https://hub.docker.com/r/siomiz/chrome/)から、(取り残されているか、`:latest`と同等だった、)`:latest`以外のタグを削除しました。
同時に`ubuntu:18.04`をベースとしたイメージを、`:18.04`タグとして登録しました。18.04.1が出るあたり(7月26日?)で`master`にマージ・`:latest`にも適応させたいと思います。
